TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true

TARGET_BOARD_PLATFORM := arm

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a

TARGET_BOOTLOADER_BOARD_NAME := iPhone

BOARD_USES_GENERIC_AUDIO := false

BOARD_KERNEL_CMDLINE := console=tty root=/dev/ram0 init=/init rw
BOARD_KERNEL_BASE := 0x09000000

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

BOARD_VENDOR_QCOM_AMSS_VERSION := 3200

#BOARD_BOOTIMAGE_PARTITION_SIZE := 0x02800000
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x07500000   # limited so we enforce room to grow
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0c440000
#BOARD_FLASH_BLOCK_SIZE := 131072

